### ISSUE TITLE
could u upload more files of this project? i have a korg d1 keyboard, but i do not have the circuit.i need your have.

### ISSUE THREAD

**Issue by ghost** [HunterWhyte/usb-midi-keyboard#1]
does your project transform a digital piano keyboard into a MIDI keyboard?

**Comment by HunterWhyte** [comment]
Sorry, these are all the files I have for this project. If I Google Korg D1 it looks like that keyboard already has a MIDI out port? Maybe you just need a MIDI to USB converter like this: https://a.co/d/2ePLoxD ?
